query eventByAuthorUsernameAndSlug(
  $authorUsername: String!
  $slug: String!
  $invitationUuid: UUID
) {
  eventByAuthorUsernameAndSlug(authorUsername: $authorUsername, slug: $slug) {
    ...eventFields
    invitationsByEventId(condition: { uuid: $invitationUuid }) {
      nodes {
        ...invitationFields
        contactByContactId {
          ...contactFields
        }
      }
    }
  }
}
