#import "../../fragments/eventFields.gql"

query allEvents($after: Cursor, $first: Int!, $authorUsername: String) {
  allEvents(
    after: $after
    condition: { authorUsername: $authorUsername }
    first: $first
    orderBy: START_DESC
  ) {
    nodes {
      ...eventFields
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
