#import "../../fragments/eventFields.gql"

query allEvents($cursor: Cursor, $limit: Int!, $authorUsername: String) {
  allEvents(
    after: $cursor
    condition: { authorUsername: $authorUsername }
    first: $limit
    orderBy: START_DESC
  ) @connection(filter: ["condition"], key: "allEvents") {
    nodes {
      ...eventFields
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
