#import "../../fragments/contactFields.gql"
#import "../../fragments/eventFields.gql"
#import "../../fragments/invitationFields.gql"

query EventByAuthorUsernameAndSlug($authorUsername: String!, $slug: String!) {
  eventByAuthorUsernameAndSlug(
    authorUsername: $authorUsername
    slug: $slug
  ) {
    ...eventFields
    invitationsByEventId(first: 1) {
      nodes {
        ...invitationFields
        contactByContactId {
        ...contactFields
        }
      }
    }
  }
}
