query allEvents($after: Cursor, $authorUsername: String, $first: Int!) {
  allEvents(
    after: $after
    condition: { authorUsername: $authorUsername }
    first: $first
    orderBy: START_DESC
  ) {
    nodes {
      ...eventFields
    }
    pageInfo {
      hasNextPage
      endCursor
    }
    totalCount
  }
}
