query($username: String, $limit: Int!, $cursor: Cursor) {
  allEvents(
    condition: { organizerUsername: $username }
    first: $limit
    after: $cursor
  ) @connection(key: "allEvents", filter: ["condition"]) {
    nodes {
      id
      name
      slug
      visibility
      organizerUsername
      description
      place
      start
      end
      archived
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
