query($cursor: Cursor, $limit: Int!, $username: String) {
  allUploads(after: $cursor, condition: { username: $username }, first: $limit)
    @connection(filter: ["condition"], key: "allUploads") {
    nodes {
      id
      sizeByte
      storageKey
      uuid
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
