query($organizerUsername: String!, $slug: String!) {
  eventContactFeedbackData(organizerUsername: $organizerUsername, slug: $slug) {
    event {
      id
      description
      end
      isArchived
      isInPerson
      isRemote
      location
      name
      organizerUsername
      slug
      start
      visibility
    }
    contact {
      id
      address
      emailAddress
      firstName
      lastName
    }
    invitationFeedbackData {
      id
      invitationFeedback
      paperInvitationFeedback
    }
  }
}
