#import "../fragments/eventFields.gql"

query EventsAll($cursor: Cursor, $limit: Int!, $username: String) {
  allEvents(
    after: $cursor
    condition: { organizerUsername: $username }
    first: $limit
  ) @connection(filter: ["condition"], key: "allEvents") {
    nodes {
      ...eventFields
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
