#import "../fragments/contactFields.gql"
#import "../fragments/eventFields.gql"
#import "../fragments/invitationFields.gql"

query EventByOrganizerUsernameAndSlug($organizerUsername: String!, $slug: String!) {
  eventByOrganizerUsernameAndSlug(
    organizerUsername: $organizerUsername
    slug: $slug
  ) {
    ...eventFields
    invitationsByEventId(first: 1) {
      nodes {
        ...invitationFields
        contactByContactId {
        ...contactFields
        }
      }
    }
  }
}
