query($organizerUsername: String!, $slug: String!) {
  eventContactFeedbackData(
    organizerUsername: $organizerUsername
    slug: $slug
  ) {
    event {
      id
      name
      slug
      visibility
      organizerUsername
      description
      place
      start
      end
      archived
    }
    contact {
      id
      firstName
      lastName
      address
      emailAddress
    }
    invitationFeedbackData {
      id
      invitationFeedback
      paperInvitationFeedback
    }
  }
}
