query($organizerUsername: String!, $slug: String!) {
  eventByOrganizerUsernameAndSlug(
    organizerUsername: $organizerUsername
    slug: $slug
  ) {
    id
    name
    slug
    visibility
    organizerUsername
    description
    place
    start
    end
    isArchived
    isInPerson
    isRemote
  }
}
