query($organizerUsername: String!, $slug: String!) {
  eventContactFeedbackData(organizerUsername: $organizerUsername, slug: $slug) {
    event {
      id
      name
      slug
      visibility
      organizerUsername
      description
      location
      start
      end
      isArchived
      isInPerson
      isRemote
    }
    contact {
      id
      firstName
      lastName
      address
      emailAddress
    }
    invitationFeedbackData {
      id
      invitationFeedback
      paperInvitationFeedback
    }
  }
}
