#import "../../fragments/uploadFields.gql"

query allUploads($first: Int!, $offset: Int, $username: String) {
  allUploads(
    condition: { username: $username }
    first: $first
    offset: $offset
  ) @connection(filter: ["condition"], key: "allUploads") {
    nodes {
      ...uploadFields
    }
    pageInfo {
      hasNextPage
    }
  }
}
