query allUploads($after: Cursor, $first: Int!, $username: String) {
  allUploads(
    after: $after
    condition: { username: $username }
    first: $first
  ) {
    nodes {
      ...uploadFields
    }
    pageInfo {
      hasNextPage
      endCursor
    }
    totalCount
  }
}
