query allInvitations($after: Cursor, $eventId: BigInt!, $first: Int!) {
  allInvitations(
    after: $after
    condition: { eventId: $eventId }
    first: $first
  ) {
    nodes {
      ...invitationFields
      contactByContactId {
        ...contactFields
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
    totalCount
  }
}
