#import "../../fragments/contactFields.gql"
#import "../../fragments/invitationFields.gql"

query InvitationsAll($eventId: BigInt!) {
  allInvitations(condition: { eventId: $eventId }) {
    nodes {
      ...invitationFields
      contactByContactId {
        ...contactFields
      }
    }
    totalCount
  }
}
