query allContacts($after: Cursor, $authorAccountUsername: String, $first: Int!) {
  allContacts(
    after: $after
    condition: { authorAccountUsername: $authorAccountUsername }
    first: $first
    orderBy: [ACCOUNT_USERNAME_ASC, FIRST_NAME_ASC, LAST_NAME_ASC]
  ) {
    nodes {
      ...contactFields
    }
    pageInfo {
      hasNextPage
      endCursor
    }
    totalCount
  }
}
